Import("*")

mixCoderCflags = CCFLAGS
mixCoderCflags.append( '-Wno-unused' )

#objects

loggerObj = env.Object('prog/fwk/log.cpp', CCFLAGS=mixCoderCflags )
mixCoderObj = env.Object('prog/MixCoder.cpp', CCFLAGS=mixCoderCflags )
audioDecoderFactoryObj = env.Object('prog/AudioDecoderFactory.cpp', CCFLAGS=mixCoderCflags )
audioSpeexDecoderObj = env.Object('prog/AudioSpeexDecoder.cpp', CCFLAGS=mixCoderCflags )
#audioFfmpegDecoderObj = env.Object('prog/AudioFfmpegDecoder.cpp', CCFLAGS=mixCoderCflags )
videoDecoderObj = env.Object('prog/VideoDecoder.cpp', CCFLAGS=mixCoderCflags )
audioSpeexEncoderObj = env.Object('prog/AudioSpeexEncoder.cpp', CCFLAGS=mixCoderCflags )
audioMp3EncoderObj = env.Object('prog/AudioMp3Encoder.cpp', CCFLAGS=mixCoderCflags )
videoEncoderObj = env.Object('prog/VideoEncoder.cpp', CCFLAGS=mixCoderCflags )
audioMixerObj = env.Object('prog/AudioMixer.cpp', CCFLAGS=mixCoderCflags )
videoMixerObj = env.Object('prog/VideoMixer.cpp', CCFLAGS=mixCoderCflags )

flvOutputObj = env.Object('prog/FLVOutput.cpp', CCFLAGS=mixCoderCflags )
flvParserObj = env.Object('prog/FLVParser.cpp', CCFLAGS=mixCoderCflags )
flvSegmentParserObj = env.Object('prog/FLVSegmentParser.cpp', CCFLAGS=mixCoderCflags )
flvSegmentOutputObj = env.Object('prog/FLVSegmentOutput.cpp', CCFLAGS=mixCoderCflags )

mainObj = env.Object('prog/MixCoderMain.cpp', CCFLAGS=mixCoderCflags )

#target
mixCoderProg = File("prog/mix_coder")

progs.append( mixCoderProg )
env.Program( mixCoderProg,
	     [ loggerObj,
	        mixCoderObj,
		audioDecoderFactoryObj,
	       audioSpeexDecoderObj,
	       videoDecoderObj,
	       audioSpeexEncoderObj,
               audioMp3EncoderObj,
	       videoEncoderObj,
	       audioMixerObj,
	       videoMixerObj,
	       flvOutputObj,
	       flvParserObj,
	       flvSegmentParserObj,
	       flvSegmentOutputObj,	
	       mainObj],	
	       LIBS=['pthread', 'mp3lame', 'avformat', 'avcodec', 'avutil', 'swscale', 'samplerate', 'speex', 'vpx'], CCFLAGS=mixCoderCflags)

#test
segOutputParserObj = env.Object('prog/SegOutputParser.cpp', CCFLAGS=mixCoderCflags )
segOutputParserProg = File("prog/seg_output_parser")

progs.append( segOutputParserProg )
env.Program( segOutputParserProg,
	     [ segOutputParserObj,
	       loggerObj ], 
	     CCFLAGS=mixCoderCflags)

segInputParserObj = env.Object('prog/SegInputParser.cpp', CCFLAGS=mixCoderCflags )
segInputParserProg = File("prog/seg_input_parser")

progs.append( segInputParserProg )
env.Program( segInputParserProg,
	     [ segInputParserObj,
	       loggerObj ], 
	     CCFLAGS=mixCoderCflags)