Import("*")

mixCoderCflags = CCFLAGS
mixCoderCflags.append( '-Wno-unused' )

#objects

mixCoderObj = env.Object('prog/MixCoder.cpp', CCFLAGS=mixCoderCflags )
audioDecoderObj = env.Object('prog/AudioDecoder.cpp', CCFLAGS=mixCoderCflags )
videoDecoderObj = env.Object('prog/VideoDecoder.cpp', CCFLAGS=mixCoderCflags )
audioEncoderObj = env.Object('prog/AudioEncoder.cpp', CCFLAGS=mixCoderCflags )
videoEncoderObj = env.Object('prog/VideoEncoder.cpp', CCFLAGS=mixCoderCflags )
audioMixerObj = env.Object('prog/AudioMixer.cpp', CCFLAGS=mixCoderCflags )
videoMixerObj = env.Object('prog/VideoMixer.cpp', CCFLAGS=mixCoderCflags )

flvOutputObj = env.Object('prog/FLVOutput.cpp', CCFLAGS=mixCoderCflags )
flvParserObj = env.Object('prog/FLVParser.cpp', CCFLAGS=mixCoderCflags )
flvSegmentParserObj = env.Object('prog/FLVSegmentParser.cpp', CCFLAGS=mixCoderCflags )
flvSegmentOutputObj = env.Object('prog/FLVSegmentOutput.cpp', CCFLAGS=mixCoderCflags )

mainObj = env.Object('prog/MixCoderMain.cpp', CCFLAGS=mixCoderCflags )

#target
mixCoderProg = File("prog/mix_coder")

progs.append( mixCoderProg )
env.Program( mixCoderProg,
	     [ mixCoderObj,
	       audioDecoderObj,
	       videoDecoderObj,
	       audioEncoderObj,
	       videoEncoderObj,
	       audioMixerObj,
	       videoMixerObj,
	       flvOutputObj,
	       flvParserObj,
	       flvSegmentParserObj,
	       flvSegmentOutputObj,	
	       mainObj],	
	       LIBS=['pthread', 'avformat', 'avcodec', 'avutil', 'swscale', 'samplerate', 'speex', 'vpx'], CCFLAGS=mixCoderCflags)

#test
segOutputParserObj = env.Object('prog/SegOutputParser.cpp', CCFLAGS=mixCoderCflags )
segOutputParserProg = File("prog/seg_output_parser")

progs.append( segOutputParserProg )
env.Program( segOutputParserProg,
	     [ segOutputParserObj ], 
	     CCFLAGS=mixCoderCflags)